Id: NotepadPlusPlus.NotepadPlusPlus
Name: NotepadPlusPlus
Version: 7.8.2
Publisher: NotepadPlusPlus
Homepage: https://notepad-plus-plus.org/downloads/v7.8.2/
License: NotepadPlusPlus
Description: Notepad++ a free (GNU) source code editor.
InstallerType: Exe
Installers:
  - Arch: x64
    Url: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.2/npp.7.8.2.Installer.exe
    Sha256: 668E6C8A666C0CB91987985BF560BF587C4FB646523FE21D3FE85B7C7EEADD08
    Switches:
      Silent: /s
      SilentWithProgress: /s
# Silent install switch does not appear to work
# At time of creation, 7.8.5 is the current version